on:
  pull_request:

name: Tests

jobs:
   UnitTest:
      runs-on: macos-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v4
           with:
              node-version: 20
         - run: npm install --no-package-lock
           name: Install dependencies
         - run: npm run build
           name: Build
         - run: npm run test
           name: Unit Test
